### ISSUE TITLE
Make build use JDK-8.

### ISSUE THREAD

**Issue by sjoerdtalsma** [talsma-ict/context-propagation#18]
Use animal sniffer to guarantee java 5 source level (and JVM class-use!) compatiblity.
Then we can at least use java 8 lambda's in unit tests etc.

**Comment by sjoerdtalsma** [comment]
JDK 8 doesn't allow source=1.8 and target=1.5, so merely adding the animal sniffer to the project won't work and retrolambda doesn't give 100% compatibility guarantees either...

**Comment by sjoerdtalsma** [comment]
Closing, won't fix.

**Comment by adriancole** [comment]
you could consider retrolambda which will rewrite the bytecode back for
you (post compile iiuc)

**Comment by sjoerdtalsma** [comment]
Thanks for the tip @adriancole 
I briefly looked into that and at that time it didn't give me quite the results I wanted.
For the moment I'll stick to non-lambda test code while thinking some more about this problem.
For JDK-9 I'll have to find a way to keep the core java-5 compatible, while also allowing newer language features (ie. compile core module with jdk <= 8 which also limits the maven multi-module build)

So I'll probably encounter this issue again at a later time anyway :wink:
