### ISSUE TITLE
Add support for Log4j2's ThreadContext

### ISSUE THREAD

**Issue by Marcono1234** [talsma-ict/context-propagation#188]
Similar to SLF4J's MDC, Log4j2 has the concept of a [`ThreadContext`](https://logging.apache.org/log4j/2.x/log4j-api/apidocs/org/apache/logging/log4j/ThreadContext.html) ([Log4j2 manual](https://logging.apache.org/log4j/2.x/manual/thread-context.html)). This ThreadContext acts both as MDC and Nested Diagnostic Context (NDC).

Creating a snapshot should use:
- [`ThreadContext.getContext()`](https://logging.apache.org/log4j/2.x/log4j-api/apidocs/org/apache/logging/log4j/ThreadContext.html#getContext--)
- [`ThreadContext.getImmutableStack()`](https://logging.apache.org/log4j/2.x/log4j-api/apidocs/org/apache/logging/log4j/ThreadContext.html#getImmutableStack--)

Reactivating a snapshot could then use Log4j2's [`CloseableThreadContext`](https://logging.apache.org/log4j/2.x/log4j-api/apidocs/org/apache/logging/log4j/CloseableThreadContext.html) which is able to revert the changes on its own:
1. Call either [`CloseableThreadContext.putAll(...)`](https://logging.apache.org/log4j/2.x/log4j-api/apidocs/org/apache/logging/log4j/CloseableThreadContext.html#putAll-java.util.Map-) or [`CloseableThreadContext.pushAll(...)`](https://logging.apache.org/log4j/2.x/log4j-api/apidocs/org/apache/logging/log4j/CloseableThreadContext.html#pushAll-java.util.List-) (with [`ContextStack.asList()`](https://logging.apache.org/log4j/2.x/log4j-api/apidocs/org/apache/logging/log4j/ThreadContext.ContextStack.html#asList--))
2. Then call either [`CloseableThreadContext.Instance.putAll(...)`](https://logging.apache.org/log4j/2.x/log4j-api/apidocs/org/apache/logging/log4j/CloseableThreadContext.Instance.html#putAll-java.util.Map-) or [`CloseableThreadContext.Instance.pushAll(...)`](https://logging.apache.org/log4j/2.x/log4j-api/apidocs/org/apache/logging/log4j/CloseableThreadContext.Instance.html#pushAll-java.util.List-) (with `ContextStack.asList()`) on the returned `CloseableThreadContext.Instance`

Then when closing the `Context` you can call [`CloseableThreadContext.Instance.close()`](https://logging.apache.org/log4j/2.x/log4j-api/apidocs/org/apache/logging/log4j/CloseableThreadContext.Instance.html#close--) to revert the changes.

The naming of the existing SLF4J MDC library (`mdc-propagation`) might be unfortunate. For Log4j2 I would propose including the library name instead, e.g. `log4j2-propagation`. Also note that just using `log4j` in the name without the "2" might lead to confusion since Log4j1 also has a [MDC](https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/MDC.html) and [NDC](https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/NDC.html), however Log4j1 is no longer supported so adding support for it here might not be needed.

I just came across your library and have not used it, but if you want I can try creating a pull request.

**Comment by sjoerdtalsma** [comment]
Thank you for bringing this to my attention.
Naturally, I welcome a pull request if you have the time for it.

A word of caution though; most time goes into testing and documentation, the actual code is only a small part of the effort in this library.
