### ISSUE TITLE
Why can Context implement Clearable?

### ISSUE THREAD

**Issue by Marcono1234** [talsma-ict/context-propagation#201]
Why is this library designed so `ContextManager` and `Context` can implement `Clearable`?
I currently cannot think of a case where only `Context` can perform the _clear_ action, so in all cases having only `ContextManager` implement `Clearable` might suffice.

**Comment by sjoerdtalsma** [comment]
Honestly? I don't know. This API kind of evolved into what it is now.

However, as it is already in the API currently it would be a breaking change to remove it. Do you have any pertinent reason to see it removed other than that it might suffice to have it only in the ContextManager (which I tend to agree to by the way)?

**Comment by Marcono1234** [comment]
No, I guess you can leave it as is. I was just slightly confused when I had a look at [`MdcManager`](https://github.com/talsma-ict/context-propagation/blob/develop/mdc-propagation/src/main/java/nl/talsmasoftware/context/mdc/MdcManager.java) and tried to figure out what `Clearable` is for.
Maybe it would be good nonetheless to document this for `Clearable` because it appears having only the manager be clearable might be slightly more efficient for `ContextManagers.clearActiveContexts()`.

Additionally the `clear` implementation for `MdcManager.MdcContext` might be wrong, it may restore the previous context instead of completely clearing it. Do you want a separate issue for that? As part of that it might be good to have `MdcManager` implement `Clearable` (respectively `ClearableContextManager`) instead.

**Comment by sjoerdtalsma** [comment]
Closing this for now, seeing you already filed #204 which is a more pertinent issue to look at.
