### ISSUE TITLE
Rename context-propagation-java5 Maven module

### ISSUE THREAD

**Issue by Marcono1234** [talsma-ict/context-propagation#205]
Personally I think the Maven module name `context-propagation-java5` is rather misleading since there is nothing specific to Java 5, it is just that Java 5 is the minimum supported version.
With #112 the module probably has to be renamed anyways.

What do you think about renaming the Maven module to just `context-propagation` (and changing the `<name>` in the POM)?

**Comment by sjoerdtalsma** [comment]
I don't quite understand the issue.

The actual maven _module_ name is `<artifactId>context-propagation</artifactId>`, so already without the `-java5` suffix.
The `-java5` only exists as a simple _subdirectory_ name.

**Comment by Marcono1234** [comment]
Sorry for not being clear enough, this issue is really only about renaming the subdirectory (and maybe changing the `<name>` in the POM of that module).

(I used the term "Maven module name" since that is how it appears in `<modules><module>` of the parent, but I am not sure if that was the correct usage of that term then.)
