### ISSUE TITLE
Stop repeatedly publishing relocation artifacts

### ISSUE THREAD

**Issue by Marcono1234** [talsma-ict/context-propagation#251]
Currently this project publishes Maven relocation artifacts for every new version. If I understand it correctly it would suffice to publish a relocation artifact once (and then remove the relocation settings from the build settings).

The [Maven Guide to relocation](https://maven.apache.org/guides/mini/guide-relocation.html) is not very explicit in that regard, but it looks like the example projects ([Ant](https://mvnrepository.com/artifact/ant/ant) and [POI](https://mvnrepository.com/artifact/poi/poi)) did it the same way.

**Comment by sjoerdtalsma** [comment]
Good point, I also understood it that way. They were just left in somehow. 
I’ll remove the now-unnecessary relocation modules, thanks for bringing this to my attention!
