### ISSUE TITLE
context-propagation-bom sets version for slf4j via context-propagation-root

### ISSUE THREAD

**Issue by vandmo** [talsma-ict/context-propagation#269]
## Expected Behavior
That the BOM only defines versions for context libraries that are part of this repository.

## Actual Behavior
I also defines a version for sl4fj. Since dependencyManagement is inherited from context-propagation-root

## Steps to Reproduce the Problem
The problem is that if you import this BOM in your own project than it will change the version of slf4j for you.

**Comment by sjoerdtalsma** [comment]
Thank you for reporting this issue!
I’ll see to it that it gets fixed asap.
