### ISSUE TITLE
NullPointerException in ScopeContext.close

### ISSUE THREAD

**Issue by hanson76** [talsma-ict/context-propagation#30]
span can be null in ScopeContext if OpentracingSpanManager is used with
ContextAware* when there is no active span. 
The problem is that ContextManagers.createContextSnapshot() only stores activeContext.getValue() which is null
ContextManagers.reactivate() then retreives null from the snapshot and calls OpentracingSpanManger.initializeNewContext(null)

The test in ScopeContext.close only checks that closed is false before calling span.close.

The fix could be to set closed to true in initializeNewContext() if span is null, 
or add a nullcheck in SpanContext.close.

**Comment by sjoerdtalsma** [comment]
Thank you for reporting this, I'll look into it this weekend!

**Comment by sjoerdtalsma** [comment]
Fixed in `0.4.14` which should be available on maven central soon.
