### ISSUE TITLE
Scope of context, when is it deleted?

### ISSUE THREAD

**Issue by nosslin579** [talsma-ict/context-propagation#57]
I decide to test some more. :smiley:

Given the common fork pool has parallelism = 3.
If you run this a couple of times you will see that Foo is always present on all three threads in the first part, as expected.
But on the second part, it is sometimes present on the thread 2 and 3, sometimes not.

I guess my question is, what is the scope of the context? When is it deleted?

```public class Main2 {
  public static void main(String[] args) throws InterruptedException {
    System.out.println(ForkJoinPool.commonPool());
    ContextAwareCompletableFuture
        .runAsync(() -> new DummyContextManager().initializeNewContext("Foo"))
        .thenCompose(aVoid1 -> {
          ContextAwareCompletableFuture<Void> future1 = ContextAwareCompletableFuture.runAsync(Main2::check);
          ContextAwareCompletableFuture<Void> future2 = ContextAwareCompletableFuture.runAsync(Main2::check);
          ContextAwareCompletableFuture<Void> future3 = ContextAwareCompletableFuture.runAsync(Main2::check);
          return CompletableFuture.allOf(future1, future2, future3);
        })
        .join();

    System.out.println("-");
    ContextAwareCompletableFuture.supplyAsync(() -> "")
        .thenCompose(aVoid1 -> {
          ContextAwareCompletableFuture<Void> future1 = ContextAwareCompletableFuture.runAsync(Main2::check);
          ContextAwareCompletableFuture<Void> future2 = ContextAwareCompletableFuture.runAsync(Main2::check);
          ContextAwareCompletableFuture<Void> future3 = ContextAwareCompletableFuture.runAsync(Main2::check);
          ContextAwareCompletableFuture<Void> future4 = ContextAwareCompletableFuture.runAsync(Main2::check);
          ContextAwareCompletableFuture<Void> future5 = ContextAwareCompletableFuture.runAsync(Main2::check);
          return CompletableFuture.allOf(future1, future2, future3, future4, future5);
        })
        .join();
  }

  private static void check() {
    try {
      Thread.sleep(100);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    DummyContextManager.currentValue().ifPresent(s1 -> System.out.println(s1 + " " + Thread.currentThread().getName()));
  }

}
```

**Comment by sjoerdtalsma** [comment]
The Context you declare that contains Foo is never closed.
It will therefore still be 'around' in the first asynchronous thread you started (CompletableFuture.runAsync(() -> Foo)) even after your lambda finished.
As the fork-join pool is used, this thread is returned to the pool.
So you have a fork-join pool populated with x threads without Foo (2 if you say the pool has size 3) and one with Foo. There is no guarantee which thread is used to schedule the futures 1..5, so some may have Foo and some may not.

So the scope of the context is from creation to closing. If you don't close the context, it will live on. Combining this with thread pools leads to unexpected behaviour as you have seen and is usually considered a memory leak, as the AbstractThreadLocalContext will 'stack' (keeping the previous context so it can restore it upon closing).

I hope this explains the sometimes part of your question?

**Comment by sjoerdtalsma** [comment]
@nosslin579 This issue looks stale. I intend to close in >24h.  
Is this question answered to your satisfaction?

**Comment by nosslin579** [comment]
Yes, thanks for the answer.

**Comment by sjoerdtalsma** [comment]
Closing
