### ISSUE TITLE
Commit e865791 has a big impact on performance of ContextManagers.createContextSnapshot()

### ISSUE THREAD

**Issue by hanson76** [talsma-ict/context-propagation#78]
The removal of the ServiceLoader cache has a large impact on the performance of this library.
ServiceLoader is only caching found providers in one instance, creating a new ServiceLoader on every call to ContextManagers.createContextSnapshot() is triggering a full classpath scanning.

We are not running in any application server, we run a plain Spring Boot 2.1 application.

My suggestion is that ServiceLoader caching is made configurable or that the providers that ServiceLoader finds are cached in a hash with the class loder as key or similar solution where ServiceLoader only has to be called once.

**Comment by sjoerdtalsma** [comment]
@hanson76 Thanks for reporting this.
Do you have measurements showing this?

Concerns about cache removal of the cache was the reason I added timing metrics to the library.

I like your idea of making this configurable. Wondering about what a sensible default might be though. What if we could do a one-time ClassLoader analysis to determine whether caching should be enabled or disabled by default (so the default is sensible, depending on how it runs). Running as simple 'main' app, spring-boot or dropwizard etc. should default to caching and JEE environments should default to no caching. Of course either of which being overridable by explicit configuration.

Any ideas on how we should handle this?

**Comment by hanson76** [comment]
I only have large flightrecordings from an application with and without caching.
The recording without caching  has the ServiceLoader as #1 "hot method". 
The flightrecording is 10 minute of a several hours long loadtest where we took the recording after the loadtest had run for some time to make sure we had a stable state on the jvm etc.

It should be easy to create a simple unit test that  calls createContextSnapshot() in a loop and calculate an average cost of the method call. It will be with a very small classpath but it will probably show the impact of the caching.

**Comment by sjoerdtalsma** [comment]
@hanson76 What do you think of this idea:

1. We make the caching configurable using System properties and/or Environment variables
2. If no configuration is provided
  - Find all ContextManagers (have to do this anyway)
  - If _all found contextmanagers_ share the Classloader with the `ContextManagers` class (and at least 1 was found), enable caching by default.

If I'm right about this idea, caching would be enabled-by-default on simple classloading hierarchies (and therefore cacheable) while still defaulting to `false` on more complex JEE type applications.

Am I right?

**Comment by hanson76** [comment]
That sounds reasonable, I don't have any JEE type application to verify with. 
I'm happy with whatever default as long as it is configurable.

Start with it being configurable and have it not cache by default to be backward compatible.
Then add more advanced way to set the default in a later version.

**Comment by sjoerdtalsma** [comment]
Should be fixed in `1.0.2`
