### ISSUE TITLE
ContextAwareCompletableFuture.thenCompose() together with supplyAsync() under Java 11

### ISSUE THREAD

**Issue by hanson76** [talsma-ict/context-propagation#97]
## Expected Behavior
ContextAwareCompletableFuture.thenCompose() works under Java 11 when the
composed CompletableFuture is created with supplyAsync or runAsync

## Actual Behavior
A NoContextManagersFound exception is being thrown.

The problem is that ProjectAppliction.compose() is executed from the ForkJoinPool.commonPool
thread pool which is using the "System" class loader (jdk.internal.loader.ClassLoaders$AppClassLoader)
instead of The class loader that the Spring Boot application has loaded all classes into (org.springframework.boot.loader.LaunchedURLClassLoader).
The ContextAwareCompletableFuture.supplyAsync() within ProjectAppliction.compose() will then try to create a new snapshot and load managers from the "wrong" classloader.

My current solution is to inject a ThreadFactory into ForkJoinPool.commonPool. The attached project can be built with -Pworkaround to enable this. Is has to do some tricks with maven antrun plugin to inject a class into the jar....

The only viable but somewhat ugly fix for this that I have come up with is to add thenCompose() methods that takes a BiFunction<? super T, ContextSnapshot, ? extends CompletionStage<U>>.  or take a Function<ValueWithContext<? super T>, ? extends CompletionStage<U>>.

That way you can pass the ContextSnapshot to ContextAwareCompletableFuture.supplyAsync() to avoid the call to createContextSnapshot() and therefor avoid the ServiceLoader trying to load classes in the wrong classloader.

There is also a fix that is using a ThreadLocal to pass the ContextSnapshot between the ContextAwareCompletableFuture that executes the thenCompose() and any ContextAware code that needs to call ContextManagers.createContextSnapshot from within the method that theCompose calls, 
 that is ugly in another way and probably has problems in it's own.

## Steps to Reproduce the Problem

  1. Unzip attached project 
  2. mvn install && java -jar target/project-1.0-SNAPSHOT.jar
  3. Notice that exception is being thrown from the call to supplyAsync at ProjectApplication.java:52

## Specifications

  - Version: 1.0.4
  - Platform: Any
  - Java version:  OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
  - (If open source) Project link: [test-project-2.zip](https://github.com/talsma-ict/context-propagation/files/2789241/test-project-2.zip)

**Comment by sjoerdtalsma** [comment]
I am hesitant to change the behaviour as it is now for reasons of predictability.
Right now, I know where each snapshot gets the context values from: the ContextManagers registered in the current thread's ContextClassLoader. Changing this behaviour means more difficulty troubleshooting problems.

Have you tried creating a ContextSnapshot explicitly and calling `supplyAsync(X, null, snapshot)` instead of `supplyAsync`? In theory this should work even from within the fork-join pool as you take the snapshot from the application code (and its classloader). I realize this is not what you are using _automatic_ context propagation for, but at least the one snapshot can contain all your threadlocal values at once.

**Comment by hanson76** [comment]
I understand, wanted to write up my findings on the "corner case" I found that actually is common and not a corner case at all. Will probably go for the custom thread factory solution for now. It's not that bad except for the antrun task I need to use.

**Comment by hanson76** [comment]
There is one other way and that is to add a configuration that switches PriorityServiceLoader from
per classloader cache to one chache for all classloaders. I also think that is more inline with the two
different modes that the current config was added for. 
Are we running in a multi classloaders environment or with just one classloader.

**Comment by sjoerdtalsma** [comment]
> There is one other way and that is to add a configuration that switches PriorityServiceLoader from
per classloader cache to one chache for all classloaders.

Interesting thought. Although I prefer some kind of 'classloader override' configuration option and use that to effectively render the cache a single-classloader cache indirectly.
I fear we will have a meta-problem of obtaining the classloader instance (by configured name?) from the fork-join pool if it gets the first 'hit' I guess...

**Comment by sjoerdtalsma** [comment]
Maybe a static `ContextManagers.setApplicationClassLoader(ClassLoader)` method could be a usable workaround? Not quite the same as a configurable property, but without the meta-problem of obtaining the classloader instance from the system classloader

**Comment by hanson76** [comment]
That looks like a good solution.

**Comment by sjoerdtalsma** [comment]
Will create a `1.0.5` release with this change in it.
