### ISSUE TITLE
Implement versions of all public static CompletableFuture methods

### ISSUE THREAD

**Issue by hanson76** [talsma-ict/context-propagation#98]
CompletableFuture has couple of static methods to create CompletableFuture instances.
ContextAwareCompletableFuture overrides a few of these today. runAsync() and supplyAsync().

ContextAwareCompletableFuture should also override completedFuture(U) and implement 
failedFuture(Throwable) that was introduced in Java 9. Maybe even introduce a context-propagation-java9 module that implements all methods of java 9 version of CompletableFuture.

ContextAwareCompletableFuture.completedFuture(U) is a priority as it is easy to misunderstand it today and think that it returns a ContextAwareCompletableFuture when it actually is returning a standard CompletableFuture where the Async methods do not copy contexts.

**Comment by sjoerdtalsma** [comment]
Agreed, I don't think it would be a problem to add the new Java 9 static method to the class in the Java 8 module though. They are static methods anyway.

**Comment by sjoerdtalsma** [comment]
Will create a `1.0.5` release with this change in it
